/**
 * Public company job boards scanned automatically for every user. Seeded from career-ops'
 * templates/portals.example.yml (MIT, see THIRD_PARTY_NOTICES.md) plus widely known employers whose
 * boards were verified live. Boards that disappear are skipped and logged, never fatal.
 */
export const BOARD_CATALOG: ReadonlyArray<{ kind: 'greenhouse' | 'lever' | 'ashby'; identifier: string; name: string }> = [
  {"kind": "greenhouse", "identifier": "anthropic", "name": "Anthropic"},
  {"kind": "greenhouse", "identifier": "polyai", "name": "PolyAI"},
  {"kind": "greenhouse", "identifier": "parloa", "name": "Parloa"},
  {"kind": "greenhouse", "identifier": "intercom", "name": "Intercom"},
  {"kind": "greenhouse", "identifier": "humeai", "name": "Hume AI"},
  {"kind": "ashby", "identifier": "elevenlabs", "name": "ElevenLabs"},
  {"kind": "ashby", "identifier": "deepgram", "name": "Deepgram"},
  {"kind": "ashby", "identifier": "vapi", "name": "Vapi"},
  {"kind": "ashby", "identifier": "bland", "name": "Bland AI"},
  {"kind": "greenhouse", "identifier": "airtable", "name": "Airtable"},
  {"kind": "greenhouse", "identifier": "vercel", "name": "Vercel"},
  {"kind": "greenhouse", "identifier": "arizeai", "name": "Arize AI"},
  {"kind": "greenhouse", "identifier": "coreweave", "name": "Weights & Biases (CoreWeave)"},
  {"kind": "greenhouse", "identifier": "gleanwork", "name": "Glean"},
  {"kind": "ashby", "identifier": "sierra", "name": "Sierra"},
  {"kind": "ashby", "identifier": "decagon", "name": "Decagon"},
  {"kind": "greenhouse", "identifier": "speechmatics", "name": "Speechmatics"},
  {"kind": "ashby", "identifier": "n8n", "name": "n8n"},
  {"kind": "ashby", "identifier": "zapier", "name": "Zapier"},
  {"kind": "greenhouse", "identifier": "boomilp", "name": "Boomi"},
  {"kind": "ashby", "identifier": "cohere", "name": "Cohere"},
  {"kind": "ashby", "identifier": "langchain", "name": "LangChain"},
  {"kind": "ashby", "identifier": "pinecone", "name": "Pinecone"},
  {"kind": "lever", "identifier": "mistral", "name": "Mistral AI"},
  {"kind": "lever", "identifier": "palantir", "name": "Palantir"},
  {"kind": "greenhouse", "identifier": "later", "name": "Later"},
  {"kind": "greenhouse", "identifier": "safariai", "name": "Safari AI"},
  {"kind": "greenhouse", "identifier": "hootsuite", "name": "Hootsuite"},
  {"kind": "ashby", "identifier": "klue", "name": "Klue"},
  {"kind": "ashby", "identifier": "glacis-ai", "name": "Glacis AI"},
  {"kind": "ashby", "identifier": "attio", "name": "Attio"},
  {"kind": "ashby", "identifier": "perk", "name": "Travelperk"},
  {"kind": "ashby", "identifier": "AlephAlpha", "name": "Aleph Alpha"},
  {"kind": "ashby", "identifier": "DeepL", "name": "DeepL"},
  {"kind": "greenhouse", "identifier": "helsing", "name": "Helsing"},
  {"kind": "greenhouse", "identifier": "celonis", "name": "Celonis"},
  {"kind": "greenhouse", "identifier": "contentful", "name": "Contentful"},
  {"kind": "greenhouse", "identifier": "getyourguide", "name": "GetYourGuide"},
  {"kind": "greenhouse", "identifier": "hellofresh", "name": "HelloFresh"},
  {"kind": "greenhouse", "identifier": "n26", "name": "N26"},
  {"kind": "greenhouse", "identifier": "traderepublicbank", "name": "Trade Republic"},
  {"kind": "greenhouse", "identifier": "sumup", "name": "SumUp"},
  {"kind": "lever", "identifier": "qonto", "name": "Qonto"},
  {"kind": "ashby", "identifier": "forto", "name": "Forto"},
  {"kind": "ashby", "identifier": "lakera.ai", "name": "Lakera"},
  {"kind": "greenhouse", "identifier": "scandit", "name": "Scandit"},
  {"kind": "ashby", "identifier": "cradlebio", "name": "Cradle"},
  {"kind": "ashby", "identifier": "photoroom", "name": "Photoroom"},
  {"kind": "lever", "identifier": "pigment", "name": "Pigment"},
  {"kind": "greenhouse", "identifier": "isomorphiclabs", "name": "Isomorphic Labs"},
  {"kind": "greenhouse", "identifier": "physicsx", "name": "PhysicsX"},
  {"kind": "greenhouse", "identifier": "stabilityai", "name": "Stability AI"},
  {"kind": "ashby", "identifier": "synthesia", "name": "Synthesia"},
  {"kind": "ashby", "identifier": "faculty", "name": "Faculty"},
  {"kind": "ashby", "identifier": "causaly", "name": "Causaly"},
  {"kind": "ashby", "identifier": "lovable", "name": "Lovable"},
  {"kind": "ashby", "identifier": "legora", "name": "Legora"},
  {"kind": "lever", "identifier": "spotify", "name": "Spotify"},
  {"kind": "ashby", "identifier": "bolt", "name": "Bolt"},
  {"kind": "ashby", "identifier": "mollie", "name": "Mollie"},
  {"kind": "lever", "identifier": "contentsquare", "name": "Hotjar"},
  {"kind": "ashby", "identifier": "corti", "name": "Corti"},
  {"kind": "ashby", "identifier": "pleo", "name": "Pleo"},
  {"kind": "greenhouse", "identifier": "amplemarket", "name": "Amplemarket"},
  {"kind": "ashby", "identifier": "perplexity", "name": "Perplexity"},
  {"kind": "ashby", "identifier": "claylabs", "name": "Clay Labs"},
  {"kind": "ashby", "identifier": "workos", "name": "WorkOS"},
  {"kind": "ashby", "identifier": "supabase", "name": "Supabase"},
  {"kind": "ashby", "identifier": "resend", "name": "Resend"},
  {"kind": "ashby", "identifier": "clerk", "name": "Clerk"},
  {"kind": "ashby", "identifier": "inngest", "name": "Inngest"},
  {"kind": "greenhouse", "identifier": "planetscale", "name": "PlanetScale"},
  {"kind": "greenhouse", "identifier": "moniepoint", "name": "Moniepoint"},
  {"kind": "greenhouse", "identifier": "jumia", "name": "Jumia"},
  {"kind": "ashby", "identifier": "andela", "name": "Andela"},
  {"kind": "greenhouse", "identifier": "airbnb", "name": "Airbnb"},
  {"kind": "greenhouse", "identifier": "stripe", "name": "Stripe"},
  {"kind": "greenhouse", "identifier": "coinbase", "name": "Coinbase"},
  {"kind": "greenhouse", "identifier": "robinhood", "name": "Robinhood"},
  {"kind": "greenhouse", "identifier": "figma", "name": "Figma"},
  {"kind": "greenhouse", "identifier": "discord", "name": "Discord"},
  {"kind": "greenhouse", "identifier": "dropbox", "name": "Dropbox"},
  {"kind": "greenhouse", "identifier": "reddit", "name": "Reddit"},
  {"kind": "greenhouse", "identifier": "pinterest", "name": "Pinterest"},
  {"kind": "greenhouse", "identifier": "lyft", "name": "Lyft"},
  {"kind": "greenhouse", "identifier": "instacart", "name": "Instacart"},
  {"kind": "greenhouse", "identifier": "gitlab", "name": "GitLab"},
  {"kind": "greenhouse", "identifier": "cloudflare", "name": "Cloudflare"},
  {"kind": "greenhouse", "identifier": "datadog", "name": "Datadog"},
  {"kind": "greenhouse", "identifier": "databricks", "name": "Databricks"},
  {"kind": "greenhouse", "identifier": "twilio", "name": "Twilio"},
  {"kind": "greenhouse", "identifier": "asana", "name": "Asana"},
  {"kind": "greenhouse", "identifier": "brex", "name": "Brex"},
  {"kind": "greenhouse", "identifier": "gusto", "name": "Gusto"},
  {"kind": "greenhouse", "identifier": "duolingo", "name": "Duolingo"},
  {"kind": "greenhouse", "identifier": "squarespace", "name": "Squarespace"},
  {"kind": "greenhouse", "identifier": "affirm", "name": "Affirm"},
  {"kind": "greenhouse", "identifier": "chime", "name": "Chime"},
  {"kind": "greenhouse", "identifier": "roblox", "name": "Roblox"},
  {"kind": "greenhouse", "identifier": "samsara", "name": "Samsara"},
  {"kind": "greenhouse", "identifier": "okta", "name": "Okta"},
  {"kind": "greenhouse", "identifier": "elastic", "name": "Elastic"},
  {"kind": "greenhouse", "identifier": "mongodb", "name": "MongoDB"},
  {"kind": "greenhouse", "identifier": "doordashusa", "name": "DoorDash"},
  {"kind": "greenhouse", "identifier": "carta", "name": "Carta"},
  {"kind": "greenhouse", "identifier": "toast", "name": "Toast"},
  {"kind": "greenhouse", "identifier": "zscaler", "name": "Zscaler"},
  {"kind": "greenhouse", "identifier": "peloton", "name": "Peloton"},
  {"kind": "greenhouse", "identifier": "betterment", "name": "Betterment"},
  {"kind": "greenhouse", "identifier": "oscar", "name": "Oscar"},
  {"kind": "greenhouse", "identifier": "flexport", "name": "Flexport"},
  {"kind": "greenhouse", "identifier": "checkr", "name": "Checkr"},
  {"kind": "greenhouse", "identifier": "webflow", "name": "Webflow"},
  {"kind": "greenhouse", "identifier": "monzo", "name": "Monzo"},
  {"kind": "greenhouse", "identifier": "gocardless", "name": "GoCardless"},
  {"kind": "greenhouse", "identifier": "wise", "name": "Wise"},
  {"kind": "greenhouse", "identifier": "deliveroo", "name": "Deliveroo"},
  {"kind": "greenhouse", "identifier": "twitch", "name": "Twitch"},
  {"kind": "greenhouse", "identifier": "scaleai", "name": "Scale AI"},
  {"kind": "greenhouse", "identifier": "sofi", "name": "SoFi"},
  {"kind": "greenhouse", "identifier": "calendly", "name": "Calendly"},
  {"kind": "greenhouse", "identifier": "lattice", "name": "Lattice"},
  {"kind": "greenhouse", "identifier": "faire", "name": "Faire"},
  {"kind": "greenhouse", "identifier": "mercury", "name": "Mercury"},
  {"kind": "greenhouse", "identifier": "pagerduty", "name": "PagerDuty"},
  {"kind": "greenhouse", "identifier": "newrelic", "name": "New Relic"},
  {"kind": "greenhouse", "identifier": "sumologic", "name": "Sumo Logic"},
  {"kind": "greenhouse", "identifier": "fivetran", "name": "Fivetran"},
  {"kind": "greenhouse", "identifier": "mixpanel", "name": "Mixpanel"},
  {"kind": "greenhouse", "identifier": "klaviyo", "name": "Klaviyo"},
  {"kind": "greenhouse", "identifier": "attentive", "name": "Attentive"},
  {"kind": "greenhouse", "identifier": "braze", "name": "Braze"},
  {"kind": "greenhouse", "identifier": "andurilindustries", "name": "Anduril"},
  {"kind": "greenhouse", "identifier": "tripactions", "name": "Navan"},
  {"kind": "greenhouse", "identifier": "qualtrics", "name": "Qualtrics"},
  {"kind": "greenhouse", "identifier": "calm", "name": "Calm"},
  {"kind": "greenhouse", "identifier": "talkspace", "name": "Talkspace"},
  {"kind": "greenhouse", "identifier": "zocdoc", "name": "Zocdoc"},
  {"kind": "greenhouse", "identifier": "khanacademy", "name": "Khan Academy"},
  {"kind": "greenhouse", "identifier": "coursera", "name": "Coursera"},
  {"kind": "greenhouse", "identifier": "udemy", "name": "Udemy"},
  {"kind": "greenhouse", "identifier": "masterclass", "name": "MasterClass"},
  {"kind": "greenhouse", "identifier": "nextdoor", "name": "Nextdoor"},
  {"kind": "lever", "identifier": "binance", "name": "Binance"},
  {"kind": "lever", "identifier": "ro", "name": "Ro"},
  {"kind": "lever", "identifier": "zoox", "name": "Zoox"},
  {"kind": "lever", "identifier": "outreach", "name": "Outreach"},
  {"kind": "lever", "identifier": "shieldai", "name": "Shield AI"},
  {"kind": "lever", "identifier": "swile", "name": "Swile"},
  {"kind": "lever", "identifier": "jobandtalent", "name": "Jobandtalent"},
  {"kind": "ashby", "identifier": "openai", "name": "OpenAI"},
  {"kind": "ashby", "identifier": "ramp", "name": "Ramp"},
  {"kind": "ashby", "identifier": "linear", "name": "Linear"},
  {"kind": "ashby", "identifier": "notion", "name": "Notion"},
  {"kind": "ashby", "identifier": "replit", "name": "Replit"},
  {"kind": "ashby", "identifier": "posthog", "name": "PostHog"},
  {"kind": "ashby", "identifier": "cursor", "name": "Cursor"},
  {"kind": "ashby", "identifier": "runway", "name": "Runway"},
  {"kind": "ashby", "identifier": "harvey", "name": "Harvey"},
  {"kind": "ashby", "identifier": "modal", "name": "Modal"},
  {"kind": "ashby", "identifier": "vanta", "name": "Vanta"},
  {"kind": "ashby", "identifier": "drata", "name": "Drata"},
  {"kind": "ashby", "identifier": "plaid", "name": "Plaid"},
  {"kind": "ashby", "identifier": "watershed", "name": "Watershed"},
  {"kind": "ashby", "identifier": "airbyte", "name": "Airbyte"},
  {"kind": "ashby", "identifier": "hex", "name": "Hex"},
  {"kind": "ashby", "identifier": "temporal", "name": "Temporal"},
  {"kind": "ashby", "identifier": "neon", "name": "Neon"},
  {"kind": "ashby", "identifier": "railway", "name": "Railway"},
  {"kind": "ashby", "identifier": "render", "name": "Render"},
  {"kind": "ashby", "identifier": "1password", "name": "1Password"},
  {"kind": "ashby", "identifier": "snyk", "name": "Snyk"},
  {"kind": "ashby", "identifier": "persona", "name": "Persona"},
  {"kind": "ashby", "identifier": "unit", "name": "Unit"},
  {"kind": "ashby", "identifier": "column", "name": "Column"},
];
